/**
 * Framework Configuration Service (Layer 2)
 * 
 * Reads framework-config.mjs (if exists) from workspace root and broadcasts
 * configuration to webview. Also tracks PRU consumption from logs.
 * 
 * Integration with gene2-core v2.0.1:
 * - Reads framework-config.mjs generated by init-client-repo.mjs
 * - Provides defaults if file doesn't exist (YOLO mode)
 * - Monitors logs/ for PRU consumption tracking
 */

import { EventEmitter } from 'events';
import * as vscode from 'vscode';
import * as fs from 'fs';
import * as path from 'path';
import {
	FrameworkConfig,
	PRUMetrics,
	getDefaultFrameworkConfig,
	getDefaultPRUMetrics,
	FrameworkConfigMessage,
} from './frameworkConfigTypes.js';

export class FrameworkConfigService extends EventEmitter {
	private workspaceRoot: string;
	private currentConfig: FrameworkConfig;
	private currentPRU: PRUMetrics;
	private fileWatcher: vscode.FileSystemWatcher | null = null;
	private outputChannel: vscode.OutputChannel | undefined;
	private debounceTimer: NodeJS.Timeout | null = null;
	private readonly DEBOUNCE_INTERVAL = 30000; // 30 seconds (was 5 min - too slow for real-time dashboard)

	constructor(
		workspaceRoot: string,
		outputChannel?: vscode.OutputChannel
	) {
		super();
		this.workspaceRoot = workspaceRoot;
		this.outputChannel = outputChannel;
		this.currentConfig = getDefaultFrameworkConfig();
		this.currentPRU = getDefaultPRUMetrics();
	}

	/**
	 * Initialize service by reading framework-config.mjs and calculating initial PRU metrics
	 */
	async initialize(): Promise<void> {
		// Read framework config
		this.currentConfig = await this.readFrameworkConfig();
		
		// Calculate initial PRU metrics
		this.currentPRU = await this.calculatePRUMetrics();
		
		this.log(`Framework config loaded: TDD=${this.currentConfig.tddMode}, BDD=${this.currentConfig.bddMode}, DDD=${this.currentConfig.dddMode}`);
		this.log(`PRU consumption: ${this.currentPRU.currentConsumption} (estimated completion: ${this.currentPRU.estimatedCompletion})`);
	}

	/**
	 * Start monitoring framework-config.mjs for changes (debounced to 5 minutes)
	 */
	startMonitoring(callback: (message: FrameworkConfigMessage) => void): void {
		// Watch framework-config.mjs and logs/ for changes
		const pattern = new vscode.RelativePattern(
			this.workspaceRoot,
			'{framework-config.mjs,logs/**/*.md}'
		);
		
		this.fileWatcher = vscode.workspace.createFileSystemWatcher(pattern);
		
		const debouncedUpdate = async (uri: vscode.Uri) => {
			if (this.debounceTimer) {
				clearTimeout(this.debounceTimer);
			}
			
			this.debounceTimer = setTimeout(async () => {
				this.log(`Framework config refreshing: ${uri.fsPath}`);
				await this.initialize();
				callback(this.getMessage());
				this.debounceTimer = null;
			}, this.DEBOUNCE_INTERVAL);
		};
		
		this.fileWatcher.onDidChange(debouncedUpdate);
		this.fileWatcher.onDidCreate(debouncedUpdate);
		
		// Send initial message
		callback(this.getMessage());
	}

	/**
	 * Stop monitoring and cleanup
	 */
	dispose(): void {
		if (this.debounceTimer) {
			clearTimeout(this.debounceTimer);
			this.debounceTimer = null;
		}
		if (this.fileWatcher) {
			this.fileWatcher.dispose();
			this.fileWatcher = null;
		}
		this.removeAllListeners();
	}

	/**
	 * Get current framework config message
	 */
	getMessage(): FrameworkConfigMessage {
		return {
			type: 'framework.config',
			config: this.currentConfig,
			pruMetrics: this.currentPRU,
		};
	}

	// ── Private helpers ────────────────────────────────────────────────────────

	/**
	 * Read framework-config.mjs from workspace root
	 * Returns defaults if file doesn't exist
	 */
	private async readFrameworkConfig(): Promise<FrameworkConfig> {
		const configPath = path.join(this.workspaceRoot, 'framework-config.mjs');
		
		if (!fs.existsSync(configPath)) {
			this.log('framework-config.mjs not found, using defaults (YOLO mode)');
			return getDefaultFrameworkConfig();
		}

		try {
			// Read file as text and parse mode flags
			const content = fs.readFileSync(configPath, 'utf-8');
			
			const config: FrameworkConfig = {
				tddMode: /tddMode:\s*true/i.test(content),
				bddMode: /bddMode:\s*true/i.test(content),
				dddMode: /dddMode:\s*true/i.test(content),
				grillMeMode: /grillMeMode:\s*true/i.test(content),
				cavemanMode: /cavemanMode:\s*true/i.test(content),
				approvalMode: false, // Will be calculated below
			};
			
			// Auto-set approvalMode if TDD/BDD/DDD all false
			config.approvalMode = !config.tddMode && !config.bddMode && !config.dddMode;
			
			return config;
		} catch (error) {
			this.log(`Error reading framework-config.mjs: ${error}`);
			return getDefaultFrameworkConfig();
		}
	}

	/**
	 * Calculate PRU metrics from logs directory
	 * 
	 * Scans agent logs recursively for PRU estimates and sums them.
	 * Looks for "PRU: ~XXXX" patterns in log entries.
	 */
	private async calculatePRUMetrics(): Promise<PRUMetrics> {
		const logsDir = path.join(this.workspaceRoot, 'logs');
		
		if (!fs.existsSync(logsDir)) {
			return getDefaultPRUMetrics();
		}

		try {
			let totalPRU = 0;
			const pruPattern = /PRU:\s*~?(\d+)/gi;
			
			// Recursively scan logs/ for .md files
			const scanDirectory = (dir: string) => {
				const entries = fs.readdirSync(dir, { withFileTypes: true });
				
				for (const entry of entries) {
					const fullPath = path.join(dir, entry.name);
					
					if (entry.isDirectory()) {
						scanDirectory(fullPath);
					} else if (entry.name.endsWith('.md')) {
						const content = fs.readFileSync(fullPath, 'utf-8');
						let match;
						
						while ((match = pruPattern.exec(content)) !== null) {
							totalPRU += parseInt(match[1], 10);
						}
					}
				}
			};
			
			scanDirectory(logsDir);
			
			// Estimate completion PRU based on project status
			// Simple heuristic: current PRU * (100 / completionPercentage) - currentPRU
			// This will be refined with actual story estimates
			const estimatedCompletion = totalPRU > 0 ? Math.round(totalPRU * 1.5) : 0;
			
			return {
				currentConsumption: totalPRU,
				estimatedCompletion,
				lastUpdated: new Date(),
			};
		} catch (error) {
			this.log(`Error calculating PRU metrics: ${error}`);
			return getDefaultPRUMetrics();
		}
	}

	/**
	 * Log to output channel if available
	 */
	private log(message: string): void {
		if (this.outputChannel) {
			this.outputChannel.appendLine(`[FrameworkConfigService] ${message}`);
		}
	}
}
